Repository CESARBR/knot-babeltower, pull requests merged in 2020-03, with the labels that each got.

#43 Thing: Proxy: bug fix
  pkg/thing/delivery/http/thing_proxy.go
Labels: bug, priority: low

#47 thing: interactor: bug fix and code style changes
  pkg/thing/interactors/update_schema.go
Labels: bug, priority: medium, refactor

#57 Change thing's service development port
  internal/config/default.yaml
  internal/config/development.yaml
Labels: bug, priority: medium
