Repository CESARBR/knot-babeltower, pull requests merged in 2020-04, with the labels that each got.

#58 style: Remove log capitalization and punctuation from errors and logs
  cmd/main.go
  internal/config/config.go
  pkg/server/handler.go
  pkg/server/server.go
  pkg/thing/controllers/thing.go
  pkg/thing/delivery/amqp/client.go
  pkg/thing/delivery/amqp/connector.go
  pkg/thing/delivery/http/thing_proxy.go
  pkg/thing/interactors/register_thing.go
  pkg/thing/interactors/register_thing_test.go
  pkg/thing/interactors/request_data_test.go
  pkg/thing/interactors/unregister_thing.go
  pkg/thing/interactors/update_schema.go
  pkg/user/controllers/user.go
  pkg/user/delivery/http/user_proxy.go
  pkg/user/interactors/create_token.go
  pkg/user/interactors/create_user.go
  pkg/user/interactors/create_user_test.go
Labels: priority: low, refactor

#60 things: proxy: Fix return when fails to list
  pkg/thing/delivery/http/thing_proxy.go
Labels: bug, priority: high

#54 docs: Update pull request template
  .github/pull_request_template.md
Labels: documentation, priority: low

#61 Fix publish data handler
  pkg/server/handler.go
Labels: bug, priority: high

#59 docs: Add events API
  docs/events.md
Labels: documentation, priority: medium

#63 thing: interactor: Fix int validation
  pkg/thing/interactors/publish_data_test.go
  pkg/thing/interactors/update_data.go
  pkg/thing/interactors/update_data_test.go
Labels: bug, priority: high

#64 Fix development config
  internal/config/development.yaml
Labels: bug, priority: medium

#65 amqp: handler: Check if headers are passed
  pkg/server/handler.go
Labels: bug
